apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelpro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travelpro
  template:
    metadata:
      labels:
        app: travelpro
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: travelpro
          image: registry.gitlab.com/vaidy.shanmugam1/travelpro:801855a6c0f4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: travelpro
spec:
  type: NodePort
  selector:
    app: travelpro
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080






